version: "3.1"
services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=saas
      - MYSQL_DATABASE= dockerTraining
#      - MYSQL_USER=root


  app:
    build: ../../../../.
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/dockerTraining